service: top-quests

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /graphql
          method: post
      - http:
          path: /graphql
          method: get

package:
  exclude:
    - db/**
    - node_modules/**
    - test/**
    - src/**
    - scripts/**
    - .vscode/**
    - .gitignore
    - README.md

plugins:
  - serverless-offline
